# Generated by Django 4.2.6 on 2023-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training_materials", "0002_summarizeddocument_application_design_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarizeddocument",
            name="system_design",
            field=models.TextField(blank=True, null=True),
        ),
    ]
